parameters:
- name: deploymentName
  default: ''
- name: deploymentParameters
  default: ''
- name: location
  default: ''
- name: serviceConnection
  default: ''
- name: templatePath
  default: ''

steps:
- task: AzureCLI@2
  displayName: "Deploy Bicep Template"
  inputs:
    azureSubscription: '${{ parameters.serviceConnection }}'
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      az bicep uninstall
      az config set bicep.use_binary_from_path=false
      az bicep install                     
      az --version
      az deployment sub create \
      --name '${{ parameters.deploymentName }}' \
      --location '${{ parameters.location }}' \
      --template-file '${{ parameters.templatePath }}' \
      --parameters ${{ parameters.deploymentParameters }}